ALTER TABLE vtxo ALTER COLUMN exit_delta SET NOT NULL;
ALTER TABLE vtxo ALTER COLUMN policy_type SET NOT NULL;
ALTER TABLE vtxo ALTER COLUMN policy SET NOT NULL;
ALTER TABLE vtxo ALTER COLUMN server_pubkey SET NOT NULL;
ALTER TABLE vtxo ALTER COLUMN amount SET NOT NULL;
ALTER TABLE vtxo ALTER COLUMN anchor_point SET NOT NULL;
ALTER TABLE vtxo ALTER COLUMN vtxo_txid SET NOT NULL;
