use std::path::Path;
use std::time::Duration;

use bitcoin::{FeeRate, Network};
use log::{debug, trace};

use crate::{Bitcoind, BitcoindConfig};

/// Snapshots older than this are regenerated. Bitcoin Core considers itself
/// in IBD while its tip is more than 24h old (nMaxTipAge) and then tells its
/// peers not to relay transactions to it, so nodes started from a stale
/// snapshot never see each other's mempool transactions until a fresh block
/// is mined. Keep a wide margin below the 24h threshold so the snapshot
/// stays young for the whole test run.
const MAX_SNAPSHOT_AGE: Duration = Duration::from_secs(12 * 60 * 60);

fn is_snapshot_valid(snapshot_dir: &Path) -> bool {
	let version_file = snapshot_dir.join("version");
	if !version_file.exists() {
		return false;
	}
	// The version file is written last, so its mtime is the generation time.
	match version_file.metadata().and_then(|m| m.modified()) {
		Ok(m) if !m.elapsed().is_ok_and(|age| age < MAX_SNAPSHOT_AGE) => return false,
		Ok(_) => {},
		Err(e) if e.kind() == std::io::ErrorKind::NotFound => return false,
		Err(e) => panic!("failed to read snapshot version file mtime: {:?}", e),
	}
	// Fail loudly on read errors: silently treating them as "invalid" would
	// delete and regenerate the snapshot while other tests are copying it,
	// leaving different nodes of a single test on conflicting chains.
	match std::fs::read_to_string(&version_file) {
		Ok(stored) => stored == Bitcoind::version(),
		Err(e) if e.kind() == std::io::ErrorKind::NotFound => false,
		Err(e) => panic!("failed to read snapshot version file: {:?}", e),
	}
}

/// Open the lock file for `snapshot_dir`, creating it if needed.
///
/// Snapshot regeneration takes this lock exclusive. Processes that copy
/// the snapshot take it shared. This prevents a regeneration from
/// deleting the snapshot while another process is copying it.
pub fn open_lock_file(snapshot_dir: &Path) -> std::fs::File {
	// Ensure the parent directory exists so we can create the lock file.
	if let Some(parent) = snapshot_dir.parent() {
		std::fs::create_dir_all(parent).expect("failed to create snapshot parent dir");
	}
	std::fs::File::options()
		.create(true)
		.write(true)
		.truncate(false)
		.open(snapshot_dir.with_extension("lock"))
		.expect("failed to open snapshot lock file")
}

/// Copy the snapshot's regtest dir into `dest_dir`.
///
/// Takes the snapshot lock shared while copying, so a concurrent
/// regeneration cannot delete the snapshot mid-copy.
pub async fn copy_snapshot(snapshot_dir: &Path, dest_dir: &Path) -> anyhow::Result<()> {
	debug!("Copying snapshot from {:?}", snapshot_dir);
	let lock_file = open_lock_file(snapshot_dir);
	lock_file.lock_shared().expect("failed to lock snapshot for copying");
	std::fs::create_dir_all(dest_dir)?;
	let status = tokio::process::Command::new("cp")
		.arg("-a")
		.arg(snapshot_dir.join("regtest"))
		.arg(dest_dir)
		.status().await?;
	anyhow::ensure!(status.success(), "failed to copy bitcoind snapshot");
	Ok(())
}

/// Ensure a valid bitcoind snapshot exists at `snapshot_dir`.
///
/// Uses file locking so that concurrent test processes don't race to
/// generate the same snapshot. The first process to acquire the lock
/// generates the snapshot; others block on the lock and then find it
/// already valid.
pub async fn ensure_snapshot(snapshot_dir: &Path) {
	// Fast path: snapshot already valid, no lock needed.
	if is_snapshot_valid(snapshot_dir) {
		trace!("Bitcoind snapshot already valid at {}", snapshot_dir.display());
		return;
	}

	// Acquire an exclusive lock (blocking — other processes wait here).
	let lock_file = open_lock_file(snapshot_dir);
	lock_file.lock().expect("failed to lock snapshot lock file");

	// Double-check: another process may have generated the snapshot while
	// we were waiting for the lock.
	if is_snapshot_valid(snapshot_dir) {
		trace!("Bitcoind snapshot generated by another process, reusing");
		// Lock released on drop.
		return;
	}

	trace!("Generating bitcoind snapshot in {}", snapshot_dir.display());

	// Remove any stale/partial snapshot.
	if snapshot_dir.exists() {
		std::fs::remove_dir_all(snapshot_dir).expect("failed to remove stale snapshot");
	}

	let bitcoind = Bitcoind::new(
		"snapshot".to_string(),
		BitcoindConfig {
			datadir: snapshot_dir.to_path_buf(),
			wallet: true,
			txindex: true,
			network: Network::Regtest,
			fallback_fee: FeeRate::from_sat_per_vb(1).unwrap(),
			relay_fee: None,
			snapshot_dir: None,
		},
		None,
	);
	bitcoind.start().await.unwrap();
	bitcoind.create_wallet("central").await;
	bitcoind.prepare_funds().await;
	bitcoind.stop().await.unwrap();

	// Write version marker last — its presence signals a complete snapshot.
	std::fs::write(snapshot_dir.join("version"), Bitcoind::version())
		.expect("failed to write snapshot version file");

	debug!("Bitcoind snapshot generated successfully");
	// Lock released on drop of lock_file.
}
