use std::path::Path;

use bitcoin::{FeeRate, Network};
use log::{debug, trace};

use crate::{Bitcoind, BitcoindConfig};

fn is_snapshot_valid(snapshot_dir: &Path) -> bool {
	let version_file = snapshot_dir.join("version");
	if !version_file.exists() {
		return false;
	}
	let stored = std::fs::read_to_string(&version_file).unwrap_or_default();
	stored == Bitcoind::version()
}

/// Ensure a valid bitcoind snapshot exists at `snapshot_dir`.
///
/// Uses file locking so that concurrent test processes don't race to
/// generate the same snapshot. The first process to acquire the lock
/// generates the snapshot; others block on the lock and then find it
/// already valid.
pub async fn ensure_snapshot(snapshot_dir: &Path) {
	// Fast path: snapshot already valid, no lock needed.
	if is_snapshot_valid(snapshot_dir) {
		trace!("Bitcoind snapshot already valid at {}", snapshot_dir.display());
		return;
	}

	// Ensure the parent directory exists so we can create the lock file.
	if let Some(parent) = snapshot_dir.parent() {
		std::fs::create_dir_all(parent).expect("failed to create snapshot parent dir");
	}

	let lock_path = snapshot_dir.with_extension("lock");
	let lock_file = std::fs::File::options()
		.create(true)
		.write(true)
		.truncate(false)
		.open(&lock_path)
		.expect("failed to open snapshot lock file");

	// Acquire an exclusive lock (blocking — other processes wait here).
	lock_file.lock().expect("failed to lock snapshot lock file");

	// Double-check: another process may have generated the snapshot while
	// we were waiting for the lock.
	if is_snapshot_valid(snapshot_dir) {
		trace!("Bitcoind snapshot generated by another process, reusing");
		// Lock released on drop.
		return;
	}

	trace!("Generating bitcoind snapshot in {}", snapshot_dir.display());

	// Remove any stale/partial snapshot.
	if snapshot_dir.exists() {
		std::fs::remove_dir_all(snapshot_dir).expect("failed to remove stale snapshot");
	}

	let mut bitcoind = Bitcoind::new(
		"snapshot".to_string(),
		BitcoindConfig {
			datadir: snapshot_dir.to_path_buf(),
			wallet: true,
			txindex: true,
			network: Network::Regtest,
			fallback_fee: FeeRate::from_sat_per_vb(1).unwrap(),
			relay_fee: None,
			snapshot_dir: None,
		},
		None,
	);
	bitcoind.start().await.unwrap();
	bitcoind.create_wallet("central").await;
	bitcoind.prepare_funds().await;
	bitcoind.stop().await.unwrap();

	// Write version marker last — its presence signals a complete snapshot.
	std::fs::write(snapshot_dir.join("version"), Bitcoind::version())
		.expect("failed to write snapshot version file");

	debug!("Bitcoind snapshot generated successfully");
	// Lock released on drop of lock_file.
}
