include:
  - local: '.gitlab/tests.yml'
  - local: '.gitlab/tests-codecov.yml'
  - local: '.gitlab/helpers.yml'
  - local: '.gitlab/master-release.yml'
  - local: '.gitlab/bark-release.yml'
  - local: '.gitlab/server-release.yml'
  - local: '.gitlab/nightly-release.yml'


variables:
  GIT_DEPTH: 100
  GIT_STRATEGY: clone
  NEXTEST_PROFILE: ci
  RUSTC_WRAPPER: sccache
  SCCACHE_MEMCACHED: tcp://host.containers.internal:11211
  SCCACHE_DIRECT: true
  SWAGGER_UI_DOWNLOAD_URL: file:///home/nixuser/assets/swagger-ui/v5.30.2.zip

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
      variables:
        NEXTEST_PROFILE: ci-merge-train
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^bark-/
    - if: $CI_COMMIT_TAG =~ /^server-/
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_URL == "https://gitlab.com/ark-bitcoin/bark"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - mirror
  - prechecks
  - check-commits
  - build
  - bark-test-builds
  - test
  - post-test
  - release
  - publish

# Specifying a default image for all steps. If you specify a new before_script in a step, then this will be ignored.
default:
  tags:
    - privileged
  image:
    name: registry.2nd.dev/build:29
    pull_policy: if-not-present
  before_script:
    - sudo chown -R nixuser:nixbld "$CI_PROJECT_DIR" || true
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git config user.name "GitLab CI"
    - git config user.email "ci@second.tech"
