/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArkAddressResponse {
    #[serde(rename = "address")]
    pub address: String,
}

impl ArkAddressResponse {
    pub fn new(address: String) -> ArkAddressResponse {
        ArkAddressResponse {
            address,
        }
    }
}

