/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArkInfo {
    #[serde(rename = "htlc_expiry_delta")]
    pub htlc_expiry_delta: i32,
    #[serde(rename = "htlc_send_expiry_delta")]
    pub htlc_send_expiry_delta: i32,
    /// Indicates whether the Ark server requires clients to either provide a VTXO ownership proof, or a lightning receive token when preparing a lightning claim.
    #[serde(rename = "ln_receive_anti_dos_required")]
    pub ln_receive_anti_dos_required: bool,
    /// Maximum CLTV delta server will allow clients to request an invoice generation with.
    #[serde(rename = "max_user_invoice_cltv_delta")]
    pub max_user_invoice_cltv_delta: i32,
    /// Maximum amount of a VTXO
    #[serde(rename = "max_vtxo_amount")]
    pub max_vtxo_amount: i64,
    /// Minimum amount for a board the server will cosign
    #[serde(rename = "min_board_amount_sat")]
    pub min_board_amount_sat: i64,
    /// Number of nonces per round
    #[serde(rename = "nb_round_nonces")]
    pub nb_round_nonces: i32,
    /// The bitcoin network the server operates on
    #[serde(rename = "network")]
    pub network: String,
    /// offboard feerate in sat per kvb
    #[serde(rename = "offboard_feerate_sat_per_kvb")]
    pub offboard_feerate_sat_per_kvb: i64,
    /// The number of confirmations required to register a board vtxo
    #[serde(rename = "required_board_confirmations")]
    pub required_board_confirmations: i32,
    /// The interval between each round
    #[serde(rename = "round_interval")]
    pub round_interval: String,
    /// The Ark server pubkey
    #[serde(rename = "server_pubkey")]
    pub server_pubkey: String,
    #[serde(rename = "vtxo_exit_delta")]
    pub vtxo_exit_delta: i32,
    #[serde(rename = "vtxo_expiry_delta")]
    pub vtxo_expiry_delta: i32,
}

impl ArkInfo {
    pub fn new(htlc_expiry_delta: i32, htlc_send_expiry_delta: i32, ln_receive_anti_dos_required: bool, max_user_invoice_cltv_delta: i32, max_vtxo_amount: i64, min_board_amount_sat: i64, nb_round_nonces: i32, network: String, offboard_feerate_sat_per_kvb: i64, required_board_confirmations: i32, round_interval: String, server_pubkey: String, vtxo_exit_delta: i32, vtxo_expiry_delta: i32) -> ArkInfo {
        ArkInfo {
            htlc_expiry_delta,
            htlc_send_expiry_delta,
            ln_receive_anti_dos_required,
            max_user_invoice_cltv_delta,
            max_vtxo_amount,
            min_board_amount_sat,
            nb_round_nonces,
            network,
            offboard_feerate_sat_per_kvb,
            required_board_confirmations,
            round_interval,
            server_pubkey,
            vtxo_exit_delta,
            vtxo_expiry_delta,
        }
    }
}

