/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Balance {
    #[serde(rename = "pending_board_sat")]
    pub pending_board_sat: i64,
    #[serde(rename = "pending_exit_sat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pending_exit_sat: Option<Option<i64>>,
    #[serde(rename = "pending_in_round_sat")]
    pub pending_in_round_sat: i64,
    #[serde(rename = "pending_lightning_receive")]
    pub pending_lightning_receive: Box<models::LightningReceiveBalance>,
    #[serde(rename = "pending_lightning_send_sat")]
    pub pending_lightning_send_sat: i64,
    #[serde(rename = "spendable_sat")]
    pub spendable_sat: i64,
}

impl Balance {
    pub fn new(pending_board_sat: i64, pending_in_round_sat: i64, pending_lightning_receive: models::LightningReceiveBalance, pending_lightning_send_sat: i64, spendable_sat: i64) -> Balance {
        Balance {
            pending_board_sat,
            pending_exit_sat: None,
            pending_in_round_sat,
            pending_lightning_receive: Box::new(pending_lightning_receive),
            pending_lightning_send_sat,
            spendable_sat,
        }
    }
}

