/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Board : Describes a completed transition of funds from onchain to offchain.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Board {
    /// The [Txid] of the funding-transaction. This is the transaction that has to be confirmed onchain for the board to succeed.
    #[serde(rename = "funding_txid")]
    pub funding_txid: String,
    /// The info for each [ark::Vtxo] that was created in this board.  Currently, this is always a vector of length 1
    #[serde(rename = "vtxos")]
    pub vtxos: Vec<models::VtxoInfo>,
}

impl Board {
    /// Describes a completed transition of funds from onchain to offchain.
    pub fn new(funding_txid: String, vtxos: Vec<models::VtxoInfo>) -> Board {
        Board {
            funding_txid,
            vtxos,
        }
    }
}

