/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoardRequest {
    /// Amount of on-chain funds to board (in satoshis)
    #[serde(rename = "amount_sat")]
    pub amount_sat: i64,
}

impl BoardRequest {
    pub fn new(amount_sat: i64) -> BoardRequest {
        BoardRequest {
            amount_sat,
        }
    }
}

