/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChildTransactionInfo : Represents a child transaction for an exit transaction package with information about the origin of the transaction
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChildTransactionInfo {
    #[serde(rename = "info")]
    pub info: Box<models::TransactionInfo>,
    #[serde(rename = "origin")]
    pub origin: Box<models::ExitTxOrigin>,
}

impl ChildTransactionInfo {
    /// Represents a child transaction for an exit transaction package with information about the origin of the transaction
    pub fn new(info: models::TransactionInfo, origin: models::ExitTxOrigin) -> ChildTransactionInfo {
        ChildTransactionInfo {
            info: Box::new(info),
            origin: Box::new(origin),
        }
    }
}

