/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedResponse {
    /// Whether the wallet is currently connected to its Ark server
    #[serde(rename = "connected")]
    pub connected: bool,
}

impl ConnectedResponse {
    pub fn new(connected: bool) -> ConnectedResponse {
        ConnectedResponse {
            connected,
        }
    }
}

