/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExitTxStatus {
    ExitTxStatusOneOf(Box<models::ExitTxStatusOneOf>),
    ExitTxStatusOneOf1(Box<models::ExitTxStatusOneOf1>),
    ExitTxStatusOneOf2(Box<models::ExitTxStatusOneOf2>),
    ExitTxStatusOneOf3(Box<models::ExitTxStatusOneOf3>),
    ExitTxStatusOneOf4(Box<models::ExitTxStatusOneOf4>),
    ExitTxStatusOneOf5(Box<models::ExitTxStatusOneOf5>),
    ExitTxStatusOneOf6(Box<models::ExitTxStatusOneOf6>),
}

impl Default for ExitTxStatus {
    fn default() -> Self {
        Self::ExitTxStatusOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "verify-inputs")]
    VerifyInputs,
    #[serde(rename = "awaiting-input-confirmation")]
    AwaitingInputConfirmation,
    #[serde(rename = "needs-signed-package")]
    NeedsSignedPackage,
    #[serde(rename = "needs-replacement-package")]
    NeedsReplacementPackage,
    #[serde(rename = "needs-broadcasting")]
    NeedsBroadcasting,
    #[serde(rename = "broadcast-with-cpfp")]
    BroadcastWithCpfp,
    #[serde(rename = "confirmed")]
    Confirmed,
}

impl Default for Type {
    fn default() -> Type {
        Self::VerifyInputs
    }
}

