/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitClaimVtxosRequest {
    /// The destination Bitcoin address
    #[serde(rename = "destination")]
    pub destination: String,
    /// Sets the desired fee-rate in sats/kvB to use broadcasting exit transactions
    #[serde(rename = "fee_rate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fee_rate: Option<Option<i64>>,
    /// The ID of an exited VTXO to be claimed
    #[serde(rename = "vtxos")]
    pub vtxos: Vec<String>,
}

impl ExitClaimVtxosRequest {
    pub fn new(destination: String, vtxos: Vec<String>) -> ExitClaimVtxosRequest {
        ExitClaimVtxosRequest {
            destination,
            fee_rate: None,
            vtxos,
        }
    }
}

