/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTransactionStatus {
    /// The history of each state the exit transaction has gone through
    #[serde(rename = "history", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub history: Option<Option<Vec<models::ExitState>>>,
    /// The current state of the exit transaction
    #[serde(rename = "state")]
    pub state: Box<models::ExitState>,
    /// Each exit transaction package required for the unilateral exit
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<models::ExitTransactionPackage>>,
    /// The ID of the VTXO that is being unilaterally exited
    #[serde(rename = "vtxo_id")]
    pub vtxo_id: String,
}

impl ExitTransactionStatus {
    pub fn new(state: models::ExitState, vtxo_id: String) -> ExitTransactionStatus {
        ExitTransactionStatus {
            history: None,
            state: Box::new(state),
            transactions: None,
            vtxo_id,
        }
    }
}

