/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitListRequest {
    /// Whether to include the detailed history of the exit process
    #[serde(rename = "history", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub history: Option<Option<bool>>,
    /// Whether to include the exit transactions and their CPFP children
    #[serde(rename = "transactions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Option<bool>>,
}

impl ExitListRequest {
    pub fn new() -> ExitListRequest {
        ExitListRequest {
            history: None,
            transactions: None,
        }
    }
}

