/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf1 {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitErrorOneOf1 {
    pub fn new(error: String, height: i32, r#type: Type) -> ExitErrorOneOf1 {
        ExitErrorOneOf1 {
            error,
            height,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "block-retrieval-failure")]
    BlockRetrievalFailure,
}

impl Default for Type {
    fn default() -> Type {
        Self::BlockRetrievalFailure
    }
}

