/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf5 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "vtxo")]
    pub vtxo: String,
}

impl ExitErrorOneOf5 {
    pub fn new(r#type: Type, vtxo: String) -> ExitErrorOneOf5 {
        ExitErrorOneOf5 {
            r#type,
            vtxo,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "cyclic-exit-transactions")]
    CyclicExitTransactions,
}

impl Default for Type {
    fn default() -> Type {
        Self::CyclicExitTransactions
    }
}

