/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitClaimRequest {
    /// Claim all exited VTXOs
    #[serde(rename = "all", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub all: Option<Option<bool>>,
    /// The destination Bitcoin address
    #[serde(rename = "destination")]
    pub destination: String,
    /// The ID of an exited VTXO to be claimed
    #[serde(rename = "vtxos", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vtxos: Option<Option<Vec<String>>>,
}

impl ExitClaimRequest {
    pub fn new(destination: String) -> ExitClaimRequest {
        ExitClaimRequest {
            all: None,
            destination,
            vtxos: None,
        }
    }
}

