/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExitState : A utility type to wrap ExitState children so they can be easily serialized. This also helps with debugging a lot!
/// A utility type to wrap ExitState children so they can be easily serialized. This also helps with debugging a lot!
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExitState {
    ExitStateOneOf(Box<models::ExitStateOneOf>),
    ExitStateOneOf1(Box<models::ExitStateOneOf1>),
    ExitStateOneOf2(Box<models::ExitStateOneOf2>),
    ExitStateOneOf3(Box<models::ExitStateOneOf3>),
    ExitStateOneOf4(Box<models::ExitStateOneOf4>),
    ExitStateOneOf5(Box<models::ExitStateOneOf5>),
}

impl Default for ExitState {
    fn default() -> Self {
        Self::ExitStateOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "start")]
    Start,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting-delta")]
    AwaitingDelta,
    #[serde(rename = "claimable")]
    Claimable,
    #[serde(rename = "claim-in-progress")]
    ClaimInProgress,
    #[serde(rename = "claimed")]
    Claimed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Start
    }
}

