/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitProgressRequest {
    /// Sets the desired fee-rate in sats/kvB to use broadcasting exit transactions
    #[serde(rename = "fee_rate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fee_rate: Option<Option<i64>>,
    /// Wait until the exit is completed
    #[serde(rename = "wait", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wait: Option<Option<bool>>,
}

impl ExitProgressRequest {
    pub fn new() -> ExitProgressRequest {
        ExitProgressRequest {
            fee_rate: None,
            wait: None,
        }
    }
}

