/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTxStatusOneOf1 {
    #[serde(rename = "txids")]
    pub txids: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitTxStatusOneOf1 {
    pub fn new(txids: Vec<String>, r#type: Type) -> ExitTxStatusOneOf1 {
        ExitTxStatusOneOf1 {
            txids,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "awaiting-input-confirmation")]
    AwaitingInputConfirmation,
}

impl Default for Type {
    fn default() -> Type {
        Self::AwaitingInputConfirmation
    }
}

