/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExitTxOrigin {
    ExitTxOriginOneOf(Box<models::ExitTxOriginOneOf>),
    ExitTxOriginOneOf1(Box<models::ExitTxOriginOneOf1>),
    ExitTxOriginOneOf2(Box<models::ExitTxOriginOneOf2>),
}

impl Default for ExitTxOrigin {
    fn default() -> Self {
        Self::ExitTxOriginOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "wallet")]
    Wallet,
    #[serde(rename = "mempool")]
    Mempool,
    #[serde(rename = "block")]
    Block,
}

impl Default for Type {
    fn default() -> Type {
        Self::Wallet
    }
}

