/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitProcessingState {
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::ExitTx>,
}

impl ExitProcessingState {
    pub fn new(tip_height: i32, transactions: Vec<models::ExitTx>) -> ExitProcessingState {
        ExitProcessingState {
            tip_height,
            transactions,
        }
    }
}

