/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitClaimInProgressState {
    #[serde(rename = "claim_txid")]
    pub claim_txid: String,
    #[serde(rename = "claimable_since")]
    pub claimable_since: String,
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
}

impl ExitClaimInProgressState {
    pub fn new(claim_txid: String, claimable_since: String, tip_height: i32) -> ExitClaimInProgressState {
        ExitClaimInProgressState {
            claim_txid,
            claimable_since,
            tip_height,
        }
    }
}

