/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTxStatusOneOf6 {
    #[serde(rename = "block")]
    pub block: String,
    #[serde(rename = "child_txid")]
    pub child_txid: String,
    #[serde(rename = "origin")]
    pub origin: Box<models::ExitTxOrigin>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitTxStatusOneOf6 {
    pub fn new(block: String, child_txid: String, origin: models::ExitTxOrigin, r#type: Type) -> ExitTxStatusOneOf6 {
        ExitTxStatusOneOf6 {
            block,
            child_txid,
            origin: Box::new(origin),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "confirmed")]
    Confirmed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Confirmed
    }
}

