/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitStateOneOf3 {
    #[serde(rename = "claimable_since")]
    pub claimable_since: String,
    #[serde(rename = "last_scanned_block")]
    pub last_scanned_block: String,
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitStateOneOf3 {
    pub fn new(claimable_since: String, last_scanned_block: String, tip_height: i32, r#type: Type) -> ExitStateOneOf3 {
        ExitStateOneOf3 {
            claimable_since,
            last_scanned_block,
            tip_height,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "claimable")]
    Claimable,
}

impl Default for Type {
    fn default() -> Type {
        Self::Claimable
    }
}

