/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitProgressResponse {
    /// Block height at which all exit outputs will be spendable
    #[serde(rename = "claimable_height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub claimable_height: Option<Option<i32>>,
    /// Whether all transactions have been confirmed
    #[serde(rename = "done")]
    pub done: bool,
    /// Status of each pending exit transaction
    #[serde(rename = "exits")]
    pub exits: Vec<models::ExitProgressStatus>,
}

impl ExitProgressResponse {
    pub fn new(done: bool, exits: Vec<models::ExitProgressStatus>) -> ExitProgressResponse {
        ExitProgressResponse {
            claimable_height: None,
            done,
            exits,
        }
    }
}

