/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitStateOneOf {
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitStateOneOf {
    pub fn new(tip_height: i32, r#type: Type) -> ExitStateOneOf {
        ExitStateOneOf {
            tip_height,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "start")]
    Start,
}

impl Default for Type {
    fn default() -> Type {
        Self::Start
    }
}

