/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf13 {
    #[serde(rename = "balance")]
    pub balance: i64,
    #[serde(rename = "fee_rate_kwu")]
    pub fee_rate_kwu: i64,
    #[serde(rename = "total_fee")]
    pub total_fee: i64,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitErrorOneOf13 {
    pub fn new(balance: i64, fee_rate_kwu: i64, total_fee: i64, r#type: Type) -> ExitErrorOneOf13 {
        ExitErrorOneOf13 {
            balance,
            fee_rate_kwu,
            total_fee,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "insufficient-fee-to-start")]
    InsufficientFeeToStart,
}

impl Default for Type {
    fn default() -> Type {
        Self::InsufficientFeeToStart
    }
}

