/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitStateOneOf1 {
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::ExitTx>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitStateOneOf1 {
    pub fn new(tip_height: i32, transactions: Vec<models::ExitTx>, r#type: Type) -> ExitStateOneOf1 {
        ExitStateOneOf1 {
            tip_height,
            transactions,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "processing")]
    Processing,
}

impl Default for Type {
    fn default() -> Type {
        Self::Processing
    }
}

