/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitStateOneOf2 {
    #[serde(rename = "claimable_height")]
    pub claimable_height: i32,
    #[serde(rename = "confirmed_block")]
    pub confirmed_block: String,
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitStateOneOf2 {
    pub fn new(claimable_height: i32, confirmed_block: String, tip_height: i32, r#type: Type) -> ExitStateOneOf2 {
        ExitStateOneOf2 {
            claimable_height,
            confirmed_block,
            tip_height,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "awaiting-delta")]
    AwaitingDelta,
}

impl Default for Type {
    fn default() -> Type {
        Self::AwaitingDelta
    }
}

