/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTxOriginOneOf1 {
    /// This is the effective fee rate of the transaction (including CPFP ancestors)
    #[serde(rename = "fee_rate_kwu")]
    pub fee_rate_kwu: i64,
    /// This includes the fees of the CPFP ancestors
    #[serde(rename = "total_fee")]
    pub total_fee: i64,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitTxOriginOneOf1 {
    pub fn new(fee_rate_kwu: i64, total_fee: i64, r#type: Type) -> ExitTxOriginOneOf1 {
        ExitTxOriginOneOf1 {
            fee_rate_kwu,
            total_fee,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "mempool")]
    Mempool,
}

impl Default for Type {
    fn default() -> Type {
        Self::Mempool
    }
}

