/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf6 {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "vtxo_id")]
    pub vtxo_id: String,
}

impl ExitErrorOneOf6 {
    pub fn new(error: String, r#type: Type, vtxo_id: String) -> ExitErrorOneOf6 {
        ExitErrorOneOf6 {
            error,
            r#type,
            vtxo_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "database-vtxo-store-failure")]
    DatabaseVtxoStoreFailure,
}

impl Default for Type {
    fn default() -> Type {
        Self::DatabaseVtxoStoreFailure
    }
}

