/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTx {
    #[serde(rename = "status")]
    pub status: Box<models::ExitTxStatus>,
    #[serde(rename = "txid")]
    pub txid: String,
}

impl ExitTx {
    pub fn new(status: models::ExitTxStatus, txid: String) -> ExitTx {
        ExitTx {
            status: Box::new(status),
            txid,
        }
    }
}

