/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExitError {
    ExitErrorOneOf(Box<models::ExitErrorOneOf>),
    ExitErrorOneOf1(Box<models::ExitErrorOneOf1>),
    ExitErrorOneOf2(Box<models::ExitErrorOneOf2>),
    ExitErrorOneOf3(Box<models::ExitErrorOneOf3>),
    ExitErrorOneOf4(Box<models::ExitErrorOneOf4>),
    ExitErrorOneOf5(Box<models::ExitErrorOneOf5>),
    ExitErrorOneOf6(Box<models::ExitErrorOneOf6>),
    ExitErrorOneOf7(Box<models::ExitErrorOneOf7>),
    ExitErrorOneOf8(Box<models::ExitErrorOneOf8>),
    ExitErrorOneOf9(Box<models::ExitErrorOneOf9>),
    ExitErrorOneOf10(Box<models::ExitErrorOneOf10>),
    ExitErrorOneOf11(Box<models::ExitErrorOneOf11>),
    ExitErrorOneOf12(Box<models::ExitErrorOneOf12>),
    ExitErrorOneOf13(Box<models::ExitErrorOneOf13>),
    ExitErrorOneOf14(Box<models::ExitErrorOneOf14>),
    ExitErrorOneOf15(Box<models::ExitErrorOneOf15>),
    ExitErrorOneOf16(Box<models::ExitErrorOneOf16>),
    ExitErrorOneOf17(Box<models::ExitErrorOneOf17>),
    ExitErrorOneOf18(Box<models::ExitErrorOneOf18>),
    ExitErrorOneOf19(Box<models::ExitErrorOneOf19>),
    ExitErrorOneOf20(Box<models::ExitErrorOneOf20>),
    ExitErrorOneOf21(Box<models::ExitErrorOneOf21>),
    ExitErrorOneOf22(Box<models::ExitErrorOneOf22>),
    ExitErrorOneOf23(Box<models::ExitErrorOneOf23>),
}

impl Default for ExitError {
    fn default() -> Self {
        Self::ExitErrorOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ancestor-retrieval-failure")]
    AncestorRetrievalFailure,
    #[serde(rename = "block-retrieval-failure")]
    BlockRetrievalFailure,
    #[serde(rename = "claim-missing-inputs")]
    ClaimMissingInputs,
    #[serde(rename = "claim-fee-exceeds-output")]
    ClaimFeeExceedsOutput,
    #[serde(rename = "claim-signing-error")]
    ClaimSigningError,
    #[serde(rename = "cyclic-exit-transactions")]
    CyclicExitTransactions,
    #[serde(rename = "database-vtxo-store-failure")]
    DatabaseVtxoStoreFailure,
    #[serde(rename = "database-child-retrieval-failure")]
    DatabaseChildRetrievalFailure,
    #[serde(rename = "dust-limit")]
    DustLimit,
    #[serde(rename = "exit-package-broadcast-failure")]
    ExitPackageBroadcastFailure,
    #[serde(rename = "exit-package-finalize-failure")]
    ExitPackageFinalizeFailure,
    #[serde(rename = "exit-package-store-failure")]
    ExitPackageStoreFailure,
    #[serde(rename = "insufficient-confirmed-funds")]
    InsufficientConfirmedFunds,
    #[serde(rename = "insufficient-fee-to-start")]
    InsufficientFeeToStart,
    #[serde(rename = "internal-error")]
    InternalError,
    #[serde(rename = "invalid-exit-transaction-status")]
    InvalidExitTransactionStatus,
    #[serde(rename = "invalid-wallet-state")]
    InvalidWalletState,
    #[serde(rename = "missing-anchor-output")]
    MissingAnchorOutput,
    #[serde(rename = "missing-exit-transaction")]
    MissingExitTransaction,
    #[serde(rename = "movement-registration-failure")]
    MovementRegistrationFailure,
    #[serde(rename = "tip-retrieval-failure")]
    TipRetrievalFailure,
    #[serde(rename = "transaction-retrieval-failure")]
    TransactionRetrievalFailure,
    #[serde(rename = "vtxo-not-claimable")]
    VtxoNotClaimable,
    #[serde(rename = "vtxo-script-pub-key-invalid")]
    VtxoScriptPubKeyInvalid,
}

impl Default for Type {
    fn default() -> Type {
        Self::AncestorRetrievalFailure
    }
}

