/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitStartRequest {
    /// The ID of VTXOs to unilaterally exit
    #[serde(rename = "vtxos")]
    pub vtxos: Vec<String>,
}

impl ExitStartRequest {
    pub fn new(vtxos: Vec<String>) -> ExitStartRequest {
        ExitStartRequest {
            vtxos,
        }
    }
}

