/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf12 {
    #[serde(rename = "available")]
    pub available: i64,
    #[serde(rename = "needed")]
    pub needed: i64,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitErrorOneOf12 {
    pub fn new(available: i64, needed: i64, r#type: Type) -> ExitErrorOneOf12 {
        ExitErrorOneOf12 {
            available,
            needed,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "insufficient-confirmed-funds")]
    InsufficientConfirmedFunds,
}

impl Default for Type {
    fn default() -> Type {
        Self::InsufficientConfirmedFunds
    }
}

