/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf8 {
    #[serde(rename = "dust")]
    pub dust: i64,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "vtxo")]
    pub vtxo: i64,
}

impl ExitErrorOneOf8 {
    pub fn new(dust: i64, r#type: Type, vtxo: i64) -> ExitErrorOneOf8 {
        ExitErrorOneOf8 {
            dust,
            r#type,
            vtxo,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "dust-limit")]
    DustLimit,
}

impl Default for Type {
    fn default() -> Type {
        Self::DustLimit
    }
}

