/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "txid")]
    pub txid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitErrorOneOf {
    pub fn new(error: String, txid: String, r#type: Type) -> ExitErrorOneOf {
        ExitErrorOneOf {
            error,
            txid,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ancestor-retrieval-failure")]
    AncestorRetrievalFailure,
}

impl Default for Type {
    fn default() -> Type {
        Self::AncestorRetrievalFailure
    }
}

