/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf2 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitErrorOneOf2 {
    pub fn new(r#type: Type) -> ExitErrorOneOf2 {
        ExitErrorOneOf2 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "claim-missing-inputs")]
    ClaimMissingInputs,
}

impl Default for Type {
    fn default() -> Type {
        Self::ClaimMissingInputs
    }
}

