/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitProgressStatus {
    /// Any error that occurred during the exit process
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<Box<models::ExitError>>>,
    /// The current state of the exit transaction
    #[serde(rename = "state")]
    pub state: Box<models::ExitState>,
    /// The ID of the VTXO that is being unilaterally exited
    #[serde(rename = "vtxo_id")]
    pub vtxo_id: String,
}

impl ExitProgressStatus {
    pub fn new(state: models::ExitState, vtxo_id: String) -> ExitProgressStatus {
        ExitProgressStatus {
            error: None,
            state: Box::new(state),
            vtxo_id,
        }
    }
}

