/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitClaimedState {
    #[serde(rename = "block")]
    pub block: String,
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
    #[serde(rename = "txid")]
    pub txid: String,
}

impl ExitClaimedState {
    pub fn new(block: String, tip_height: i32, txid: String) -> ExitClaimedState {
        ExitClaimedState {
            block,
            tip_height,
            txid,
        }
    }
}

