/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitErrorOneOf18 {
    #[serde(rename = "txid")]
    pub txid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitErrorOneOf18 {
    pub fn new(txid: String, r#type: Type) -> ExitErrorOneOf18 {
        ExitErrorOneOf18 {
            txid,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "missing-exit-transaction")]
    MissingExitTransaction,
}

impl Default for Type {
    fn default() -> Type {
        Self::MissingExitTransaction
    }
}

