/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTxStatusOneOf3 {
    #[serde(rename = "min_fee")]
    pub min_fee: i64,
    #[serde(rename = "min_fee_rate_kwu")]
    pub min_fee_rate_kwu: i64,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitTxStatusOneOf3 {
    pub fn new(min_fee: i64, min_fee_rate_kwu: i64, r#type: Type) -> ExitTxStatusOneOf3 {
        ExitTxStatusOneOf3 {
            min_fee,
            min_fee_rate_kwu,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "needs-replacement-package")]
    NeedsReplacementPackage,
}

impl Default for Type {
    fn default() -> Type {
        Self::NeedsReplacementPackage
    }
}

