/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTransactionPackage {
    /// The child transaction used to spend, and thus confirm, the exit anchor output
    #[serde(rename = "child", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub child: Option<Option<Box<models::ChildTransactionInfo>>>,
    /// The actual unilateral exit transaction containing an anchor output and a spendable amount
    #[serde(rename = "exit")]
    pub exit: Box<models::TransactionInfo>,
}

impl ExitTransactionPackage {
    pub fn new(exit: models::TransactionInfo) -> ExitTransactionPackage {
        ExitTransactionPackage {
            child: None,
            exit: Box::new(exit),
        }
    }
}

