/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitStateOneOf5 {
    #[serde(rename = "block")]
    pub block: String,
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
    #[serde(rename = "txid")]
    pub txid: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitStateOneOf5 {
    pub fn new(block: String, tip_height: i32, txid: String, r#type: Type) -> ExitStateOneOf5 {
        ExitStateOneOf5 {
            block,
            tip_height,
            txid,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "claimed")]
    Claimed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Claimed
    }
}

