/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitClaimableState {
    #[serde(rename = "claimable_since")]
    pub claimable_since: String,
    #[serde(rename = "last_scanned_block", deserialize_with = "Option::deserialize")]
    pub last_scanned_block: Option<String>,
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
}

impl ExitClaimableState {
    pub fn new(claimable_since: String, last_scanned_block: Option<String>, tip_height: i32) -> ExitClaimableState {
        ExitClaimableState {
            claimable_since,
            last_scanned_block,
            tip_height,
        }
    }
}

