/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitClaimResponse {
    #[serde(rename = "message")]
    pub message: String,
}

impl ExitClaimResponse {
    pub fn new(message: String) -> ExitClaimResponse {
        ExitClaimResponse {
            message,
        }
    }
}

