/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitClaimAllRequest {
    /// The destination Bitcoin address
    #[serde(rename = "destination")]
    pub destination: String,
    /// Sets the desired fee-rate in sats/kvB to use broadcasting exit transactions
    #[serde(rename = "fee_rate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fee_rate: Option<Option<i64>>,
}

impl ExitClaimAllRequest {
    pub fn new(destination: String) -> ExitClaimAllRequest {
        ExitClaimAllRequest {
            destination,
            fee_rate: None,
        }
    }
}

