/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitTxOriginOneOf2 {
    #[serde(rename = "confirmed_in")]
    pub confirmed_in: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ExitTxOriginOneOf2 {
    pub fn new(confirmed_in: String, r#type: Type) -> ExitTxOriginOneOf2 {
        ExitTxOriginOneOf2 {
            confirmed_in,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "block")]
    Block,
}

impl Default for Type {
    fn default() -> Type {
        Self::Block
    }
}

