/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputInfo {
    #[serde(rename = "prevout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prevout: Option<Option<String>>,
    #[serde(rename = "script_sig", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub script_sig: Option<Option<Box<models::InputScriptInfo>>>,
    #[serde(rename = "sequence", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sequence: Option<Option<i32>>,
    #[serde(rename = "txid", deserialize_with = "Option::deserialize")]
    pub txid: Option<String>,
    #[serde(rename = "vout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vout: Option<Option<i32>>,
    #[serde(rename = "witness", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub witness: Option<Option<Vec<Vec<i32>>>>,
}

impl InputInfo {
    pub fn new(txid: Option<String>) -> InputInfo {
        InputInfo {
            prevout: None,
            script_sig: None,
            sequence: None,
            txid,
            vout: None,
            witness: None,
        }
    }
}

