/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceInfo {
    /// The invoice string
    #[serde(rename = "invoice")]
    pub invoice: String,
}

impl InvoiceInfo {
    pub fn new(invoice: String) -> InvoiceInfo {
        InvoiceInfo {
            invoice,
        }
    }
}

