/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightningInvoiceRequest {
    /// The amount to create invoice for (in satoshis)
    #[serde(rename = "amount_sat")]
    pub amount_sat: i64,
}

impl LightningInvoiceRequest {
    pub fn new(amount_sat: i64) -> LightningInvoiceRequest {
        LightningInvoiceRequest {
            amount_sat,
        }
    }
}

