/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightningReceiveBalance {
    #[serde(rename = "claimable_sat")]
    pub claimable_sat: i64,
    #[serde(rename = "total_sat")]
    pub total_sat: i64,
}

impl LightningReceiveBalance {
    pub fn new(claimable_sat: i64, total_sat: i64) -> LightningReceiveBalance {
        LightningReceiveBalance {
            claimable_sat,
            total_sat,
        }
    }
}

