/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightningPayResponse {
    /// Success message
    #[serde(rename = "message")]
    pub message: String,
    /// The payment preimage (for successful payments)
    #[serde(rename = "preimage")]
    pub preimage: String,
}

impl LightningPayResponse {
    pub fn new(message: String, preimage: String) -> LightningPayResponse {
        LightningPayResponse {
            message,
            preimage,
        }
    }
}

