/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightningPayRequest {
    /// The amount to send (in satoshis). Optional for bolt11 invoices with amount
    #[serde(rename = "amount_sat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount_sat: Option<Option<i64>>,
    /// An optional comment, only supported when paying to lightning addresses
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<String>>,
    /// The invoice, offer, or lightning address to pay
    #[serde(rename = "destination")]
    pub destination: String,
}

impl LightningPayRequest {
    pub fn new(destination: String) -> LightningPayRequest {
        LightningPayRequest {
            amount_sat: None,
            comment: None,
            destination,
        }
    }
}

