/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightningStatusRequest {
    /// Payment hash or invoice string
    #[serde(rename = "filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Option<String>>,
    /// Filter by preimage
    #[serde(rename = "preimage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preimage: Option<Option<String>>,
}

impl LightningStatusRequest {
    pub fn new() -> LightningStatusRequest {
        LightningStatusRequest {
            filter: None,
            preimage: None,
        }
    }
}

