/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightningStatusResponse {
    /// The invoice that was paid
    #[serde(rename = "invoice")]
    pub invoice: String,
    /// The payment hash of the invoice
    #[serde(rename = "payment_hash")]
    pub payment_hash: String,
    /// The preimage that was used to pay the invoice
    #[serde(rename = "payment_preimage")]
    pub payment_preimage: String,
    /// The time the preimage was revealed
    #[serde(rename = "preimage_revealed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preimage_revealed_at: Option<Option<String>>,
}

impl LightningStatusResponse {
    pub fn new(invoice: String, payment_hash: String, payment_preimage: String) -> LightningStatusResponse {
        LightningStatusResponse {
            invoice,
            payment_hash,
            payment_preimage,
            preimage_revealed_at: None,
        }
    }
}

