/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightningReceiveInfo {
    /// The amount of the lightning receive
    #[serde(rename = "amount_sat")]
    pub amount_sat: i64,
    /// The HTLC VTXOs granted by the server for the lightning receive  Only present if the lightning HTLC has been received by the server.
    #[serde(rename = "htlc_vtxos", deserialize_with = "Option::deserialize")]
    pub htlc_vtxos: Option<Vec<models::WalletVtxoInfo>>,
    /// The invoice string
    #[serde(rename = "invoice")]
    pub invoice: String,
    /// The payment hash linked to the lightning receive info
    #[serde(rename = "payment_hash")]
    pub payment_hash: String,
    /// The payment preimage linked to the lightning receive info
    #[serde(rename = "payment_preimage")]
    pub payment_preimage: String,
    /// The timestamp at which the preimage was revealed
    #[serde(rename = "preimage_revealed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preimage_revealed_at: Option<Option<String>>,
}

impl LightningReceiveInfo {
    pub fn new(amount_sat: i64, htlc_vtxos: Option<Vec<models::WalletVtxoInfo>>, invoice: String, payment_hash: String, payment_preimage: String) -> LightningReceiveInfo {
        LightningReceiveInfo {
            amount_sat,
            htlc_vtxos,
            invoice,
            payment_hash,
            payment_preimage,
            preimage_revealed_at: None,
        }
    }
}

