/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Movement {
    /// Movement date
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Fees paid for the movement
    #[serde(rename = "fees")]
    pub fees: i64,
    #[serde(rename = "id")]
    pub id: i32,
    /// Received VTXOs from this movement
    #[serde(rename = "receives")]
    pub receives: Vec<models::VtxoInfo>,
    /// External recipients of the movement
    #[serde(rename = "recipients")]
    pub recipients: Vec<models::RecipientInfo>,
    /// wallet's VTXOs spent in this movement
    #[serde(rename = "spends")]
    pub spends: Vec<models::VtxoInfo>,
}

impl Movement {
    pub fn new(created_at: String, fees: i64, id: i32, receives: Vec<models::VtxoInfo>, recipients: Vec<models::RecipientInfo>, spends: Vec<models::VtxoInfo>) -> Movement {
        Movement {
            created_at,
            fees,
            id,
            receives,
            recipients,
            spends,
        }
    }
}

