/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MovementTimestamp : Contains the times at which the movement was created, updated and completed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovementTimestamp {
    /// The action responsible for registering the movement.
    #[serde(rename = "completed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<String>>,
    /// When the movement was first created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// When the movement was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl MovementTimestamp {
    /// Contains the times at which the movement was created, updated and completed.
    pub fn new(created_at: String, updated_at: String) -> MovementTimestamp {
        MovementTimestamp {
            completed_at: None,
            created_at,
            updated_at,
        }
    }
}

