/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Movement : Describes an attempted movement of offchain funds within the Bark [Wallet].
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Movement {
    /// How much the wallet balance actually changed by. Positive numbers indicate an increase and negative numbers indicate a decrease. This is often inclusive of applicable fees, and it should be the most accurate number.
    #[serde(rename = "effective_balance_sat")]
    pub effective_balance_sat: i64,
    /// A list of IDs for VTXOs that were marked for unilateral exit as a result of this movement. This could happen for many reasons, e.g. an unsuccessful lightning payment which can't be revoked but is about to expire. VTXOs listed here will result in a reduction of spendable balance due to the VTXOs being managed by the [bark::Exit] system.
    #[serde(rename = "exited_vtxos")]
    pub exited_vtxos: Vec<String>,
    /// The internal ID of the movement.
    #[serde(rename = "id")]
    pub id: i32,
    /// A list of [Vtxo] IDs that were consumed by this movement and are either locked or unavailable.
    #[serde(rename = "input_vtxos")]
    pub input_vtxos: Vec<String>,
    /// How much the movement was expected to increase or decrease the balance by. This is always an estimate and often discounts any applicable fees.
    #[serde(rename = "intended_balance_sat")]
    pub intended_balance_sat: i64,
    /// Miscellaneous metadata for the movement. This is JSON containing arbitrary information as defined by the subsystem that created the movement.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// How much the movement cost the user in offchain fees. If there are applicable onchain fees they will not be included in this value but, depending on the subsystem, could be found in the metadata.
    #[serde(rename = "offchain_fee_sat")]
    pub offchain_fee_sat: i64,
    /// A list of IDs for new VTXOs that were produced as a result of this movement. Often change VTXOs will be found here for outbound actions unless this was an inbound action.
    #[serde(rename = "output_vtxos")]
    pub output_vtxos: Vec<String>,
    /// Describes the means by which the wallet received funds in this movement. This could include BOLT11 invoices or other useful data.
    #[serde(rename = "received_on")]
    pub received_on: Vec<models::MovementDestination>,
    /// A list of external recipients that received funds from this movement.
    #[serde(rename = "sent_to")]
    pub sent_to: Vec<models::MovementDestination>,
    /// The status of the movement.
    #[serde(rename = "status")]
    pub status: models::MovementStatus,
    /// Contains information about the subsystem that created the movement as well as the purpose of the movement.
    #[serde(rename = "subsystem")]
    pub subsystem: Box<models::MovementSubsystem>,
    /// Contains the times at which the movement was created, updated and completed.
    #[serde(rename = "time")]
    pub time: Box<models::MovementTimestamp>,
}

impl Movement {
    /// Describes an attempted movement of offchain funds within the Bark [Wallet].
    pub fn new(effective_balance_sat: i64, exited_vtxos: Vec<String>, id: i32, input_vtxos: Vec<String>, intended_balance_sat: i64, offchain_fee_sat: i64, output_vtxos: Vec<String>, received_on: Vec<models::MovementDestination>, sent_to: Vec<models::MovementDestination>, status: models::MovementStatus, subsystem: models::MovementSubsystem, time: models::MovementTimestamp) -> Movement {
        Movement {
            effective_balance_sat,
            exited_vtxos,
            id,
            input_vtxos,
            intended_balance_sat,
            metadata: None,
            offchain_fee_sat,
            output_vtxos,
            received_on,
            sent_to,
            status,
            subsystem: Box::new(subsystem),
            time: Box::new(time),
        }
    }
}

