/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MovementSubsystem : Contains information about the subsystem that created the movement as well as the purpose of the movement.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovementSubsystem {
    /// The action responsible for registering the movement.
    #[serde(rename = "kind")]
    pub kind: String,
    /// The name of the subsystem that created and manages the movement.
    #[serde(rename = "name")]
    pub name: String,
}

impl MovementSubsystem {
    /// Contains information about the subsystem that created the movement as well as the purpose of the movement.
    pub fn new(kind: String, name: String) -> MovementSubsystem {
        MovementSubsystem {
            kind,
            name,
        }
    }
}

