/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MovementDestination : Describes a recipient of a movement. This could either be an external recipient in send actions or it could be the bark wallet itself.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovementDestination {
    /// How many sats the recipient received.
    #[serde(rename = "amount_sat")]
    pub amount_sat: i64,
    /// An address, invoice or any other identifier to distinguish the recipient.
    #[serde(rename = "destination")]
    pub destination: String,
}

impl MovementDestination {
    /// Describes a recipient of a movement. This could either be an external recipient in send actions or it could be the bark wallet itself.
    pub fn new(amount_sat: i64, destination: String) -> MovementDestination {
        MovementDestination {
            amount_sat,
            destination,
        }
    }
}

