/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffboardAllRequest {
    /// Optional Bitcoin address to send to. If not provided, uses the onchain wallet's address
    #[serde(rename = "address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address: Option<Option<String>>,
}

impl OffboardAllRequest {
    pub fn new() -> OffboardAllRequest {
        OffboardAllRequest {
            address: None,
        }
    }
}

