/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnchainDrainRequest {
    /// The destination Bitcoin address
    #[serde(rename = "destination")]
    pub destination: String,
}

impl OnchainDrainRequest {
    pub fn new(destination: String) -> OnchainDrainRequest {
        OnchainDrainRequest {
            destination,
        }
    }
}

