/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnchainSendManyRequest {
    /// List of destinations in format \"address:amount\"
    #[serde(rename = "destinations")]
    pub destinations: Vec<String>,
    /// Sends the transaction immediately instead of waiting
    #[serde(rename = "immediate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub immediate: Option<Option<bool>>,
}

impl OnchainSendManyRequest {
    pub fn new(destinations: Vec<String>) -> OnchainSendManyRequest {
        OnchainSendManyRequest {
            destinations,
            immediate: None,
        }
    }
}

