/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnchainBalance {
    /// Confirmed and immediately spendable balance
    #[serde(rename = "confirmed_sat")]
    pub confirmed_sat: i64,
    /// All coinbase outputs not yet matured
    #[serde(rename = "immature_sat")]
    pub immature_sat: i64,
    /// All of them combined.
    #[serde(rename = "total_sat")]
    pub total_sat: i64,
    /// Unconfirmed UTXOs generated by a wallet tx
    #[serde(rename = "trusted_pending_sat")]
    pub trusted_pending_sat: i64,
    /// Get sum of trusted_pending and confirmed coins.  This is the balance you can spend right now that shouldn't get cancelled via another party double spending it.
    #[serde(rename = "trusted_spendable_sat")]
    pub trusted_spendable_sat: i64,
    /// Unconfirmed UTXOs received from an external wallet
    #[serde(rename = "untrusted_pending_sat")]
    pub untrusted_pending_sat: i64,
}

impl OnchainBalance {
    pub fn new(confirmed_sat: i64, immature_sat: i64, total_sat: i64, trusted_pending_sat: i64, trusted_spendable_sat: i64, untrusted_pending_sat: i64) -> OnchainBalance {
        OnchainBalance {
            confirmed_sat,
            immature_sat,
            total_sat,
            trusted_pending_sat,
            trusted_spendable_sat,
            untrusted_pending_sat,
        }
    }
}

