/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputScriptInfo {
    #[serde(rename = "address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address: Option<Option<String>>,
    #[serde(rename = "asm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asm: Option<Option<String>>,
    #[serde(rename = "hex", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hex: Option<Option<Vec<i32>>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
}

impl OutputScriptInfo {
    pub fn new() -> OutputScriptInfo {
        OutputScriptInfo {
            address: None,
            asm: None,
            hex: None,
            r#type: None,
        }
    }
}

