/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputInfo {
    #[serde(rename = "script_pub_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub script_pub_key: Option<Option<Box<models::OutputScriptInfo>>>,
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<i64>,
}

impl OutputInfo {
    pub fn new(value: Option<i64>) -> OutputInfo {
        OutputInfo {
            script_pub_key: None,
            value,
        }
    }
}

