/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeakAddressRequest {
    #[serde(rename = "index")]
    pub index: i32,
}

impl PeakAddressRequest {
    pub fn new(index: i32) -> PeakAddressRequest {
        PeakAddressRequest {
            index,
        }
    }
}

