/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingRoundInfo {
    /// Attempt sequence number within the round, if known
    #[serde(rename = "attempt_seq", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attempt_seq: Option<Option<i32>>,
    /// Unique identifier for the round
    #[serde(rename = "id")]
    pub id: i32,
    /// Discriminant of the round state
    #[serde(rename = "kind")]
    pub kind: String,
    /// Round sequence number, if known
    #[serde(rename = "round_seq", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub round_seq: Option<Option<i64>>,
    /// The round transaction id, if already assigned
    #[serde(rename = "round_txid", deserialize_with = "Option::deserialize")]
    pub round_txid: Option<String>,
}

impl PendingRoundInfo {
    pub fn new(id: i32, kind: String, round_txid: Option<String>) -> PendingRoundInfo {
        PendingRoundInfo {
            attempt_seq: None,
            id,
            kind,
            round_seq: None,
            round_txid,
        }
    }
}

