/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipientInfo {
    #[serde(rename = "amount_sat")]
    pub amount_sat: i64,
    /// Can either be a publickey, spk or a bolt11 invoice
    #[serde(rename = "recipient")]
    pub recipient: String,
}

impl RecipientInfo {
    pub fn new(amount_sat: i64, recipient: String) -> RecipientInfo {
        RecipientInfo {
            amount_sat,
            recipient,
        }
    }
}

