/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshRequest {
    /// List of VTXO IDs to refresh
    #[serde(rename = "vtxos")]
    pub vtxos: Vec<String>,
}

impl RefreshRequest {
    pub fn new(vtxos: Vec<String>) -> RefreshRequest {
        RefreshRequest {
            vtxos,
        }
    }
}

