/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoundStatusOneOf : The round was successful and is fully confirmed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundStatusOneOf {
    #[serde(rename = "funding_txid")]
    pub funding_txid: String,
    #[serde(rename = "result")]
    pub result: Result,
}

impl RoundStatusOneOf {
    /// The round was successful and is fully confirmed
    pub fn new(funding_txid: String, result: Result) -> RoundStatusOneOf {
        RoundStatusOneOf {
            funding_txid,
            result,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "confirmed")]
    Confirmed,
}

impl Default for Result {
    fn default() -> Result {
        Self::Confirmed
    }
}

