/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoundStatus {
    RoundStatusOneOf(Box<models::RoundStatusOneOf>),
    RoundStatusOneOf1(Box<models::RoundStatusOneOf1>),
    RoundStatusOneOf2(Box<models::RoundStatusOneOf2>),
    RoundStatusOneOf3(Box<models::RoundStatusOneOf3>),
}

impl Default for RoundStatus {
    fn default() -> Self {
        Self::RoundStatusOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Result {
    fn default() -> Result {
        Self::Failed
    }
}

