/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoundStatusOneOf1 : Round successful but not fully confirmed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundStatusOneOf1 {
    #[serde(rename = "funding_txid")]
    pub funding_txid: String,
    #[serde(rename = "result")]
    pub result: Result,
}

impl RoundStatusOneOf1 {
    /// Round successful but not fully confirmed
    pub fn new(funding_txid: String, result: Result) -> RoundStatusOneOf1 {
        RoundStatusOneOf1 {
            funding_txid,
            result,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "unconfirmed")]
    Unconfirmed,
}

impl Default for Result {
    fn default() -> Result {
        Self::Unconfirmed
    }
}

