/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoundStatusOneOf3 : The round failed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundStatusOneOf3 {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "result")]
    pub result: Result,
}

impl RoundStatusOneOf3 {
    /// The round failed
    pub fn new(error: String, result: Result) -> RoundStatusOneOf3 {
        RoundStatusOneOf3 {
            error,
            result,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Result {
    fn default() -> Result {
        Self::Failed
    }
}

