/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoundStatusOneOf2 : We have unsigned funding transactions that might confirm
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundStatusOneOf2 {
    #[serde(rename = "result")]
    pub result: Result,
    #[serde(rename = "unsigned_funding_txids")]
    pub unsigned_funding_txids: Vec<String>,
}

impl RoundStatusOneOf2 {
    /// We have unsigned funding transactions that might confirm
    pub fn new(result: Result, unsigned_funding_txids: Vec<String>) -> RoundStatusOneOf2 {
        RoundStatusOneOf2 {
            result,
            unsigned_funding_txids,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "pending")]
    Pending,
}

impl Default for Result {
    fn default() -> Result {
        Self::Pending
    }
}

