/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoundStatusOneOf4 : The round canceled
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundStatusOneOf4 {
    #[serde(rename = "result")]
    pub result: Result,
}

impl RoundStatusOneOf4 {
    /// The round canceled
    pub fn new(result: Result) -> RoundStatusOneOf4 {
        RoundStatusOneOf4 {
            result,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "canceled")]
    Canceled,
}

impl Default for Result {
    fn default() -> Result {
        Self::Canceled
    }
}

