/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendOnchainRequest {
    /// The amount to send (in satoshis)
    #[serde(rename = "amount_sat")]
    pub amount_sat: i64,
    /// The destination Bitcoin address
    #[serde(rename = "destination")]
    pub destination: String,
}

impl SendOnchainRequest {
    pub fn new(amount_sat: i64, destination: String) -> SendOnchainRequest {
        SendOnchainRequest {
            amount_sat,
            destination,
        }
    }
}

