/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TipResponse {
    #[serde(rename = "tip_height")]
    pub tip_height: i32,
}

impl TipResponse {
    pub fn new(tip_height: i32) -> TipResponse {
        TipResponse {
            tip_height,
        }
    }
}

