/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionInfo : An information struct used to pair the ID of a transaction with the full transaction for ease of use and readability for the user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionInfo {
    #[serde(rename = "tx")]
    pub tx: String,
    #[serde(rename = "txid")]
    pub txid: String,
}

impl TransactionInfo {
    /// An information struct used to pair the ID of a transaction with the full transaction for ease of use and readability for the user
    pub fn new(tx: String, txid: String) -> TransactionInfo {
        TransactionInfo {
            tx,
            txid,
        }
    }
}

