/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.2
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UtxoInfo : Struct representing information about an Unspent Transaction Output (UTXO).  This structure provides details about a UTXO, which includes the outpoint (transaction ID and index), the associated amount in satoshis, and the block height at which the transaction was confirmed (if available).  # Serde Behavior  * The `amount` field is serialized and deserialized with a custom function from the `bitcoin`   crate that ensures the value is interpreted as satoshis with the name `amount_sat`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UtxoInfo {
    /// The value of the UTXO in satoshis.
    #[serde(rename = "amount_sat")]
    pub amount_sat: i64,
    /// An optional field that specifies the block height at which the transaction was confirmed. If the transaction is unconfirmed, this value will be `None`.
    #[serde(rename = "confirmation_height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub confirmation_height: Option<Option<i32>>,
    /// Contains the reference to the specific transaction output via transaction ID and index.
    #[serde(rename = "outpoint")]
    pub outpoint: String,
}

impl UtxoInfo {
    /// Struct representing information about an Unspent Transaction Output (UTXO).  This structure provides details about a UTXO, which includes the outpoint (transaction ID and index), the associated amount in satoshis, and the block height at which the transaction was confirmed (if available).  # Serde Behavior  * The `amount` field is serialized and deserialized with a custom function from the `bitcoin`   crate that ensures the value is interpreted as satoshis with the name `amount_sat`.
    pub fn new(amount_sat: i64, outpoint: String) -> UtxoInfo {
        UtxoInfo {
            amount_sat,
            confirmation_height: None,
            outpoint,
        }
    }
}

