/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VtxoStateInfo : Describe the state of a [Vtxo] with additional context.
/// Describe the state of a [Vtxo] with additional context.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VtxoStateInfo {
    VtxoStateInfoOneOf(Box<models::VtxoStateInfoOneOf>),
    VtxoStateInfoOneOf1(Box<models::VtxoStateInfoOneOf1>),
    VtxoStateInfoOneOf2(Box<models::VtxoStateInfoOneOf2>),
}

impl Default for VtxoStateInfo {
    fn default() -> Self {
        Self::VtxoStateInfoOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "spendable")]
    Spendable,
    #[serde(rename = "spent")]
    Spent,
    #[serde(rename = "locked")]
    Locked,
}

impl Default for Type {
    fn default() -> Type {
        Self::Spendable
    }
}

