/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtxosQuery {
    /// Return all VTXOs regardless of their state (including spent ones)
    #[serde(rename = "all", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub all: Option<Option<bool>>,
}

impl VtxosQuery {
    pub fn new() -> VtxosQuery {
        VtxosQuery {
            all: None,
        }
    }
}

