/*
 * Barkd API
 *
 * A simple REST API for Barkd
 *
 * The version of the OpenAPI document: 0.1.0-beta.4
 * Contact: hello@second.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtxoStateInfoOneOf {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl VtxoStateInfoOneOf {
    pub fn new(r#type: Type) -> VtxoStateInfoOneOf {
        VtxoStateInfoOneOf {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "spendable")]
    Spendable,
}

impl Default for Type {
    fn default() -> Type {
        Self::Spendable
    }
}

