when:
  - event: pull_request
  - event: manual
  - event: tag
  - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://gitlab.com/ark-bitcoin/bark"'

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: tar-and-print-test-data
    image: registry.2nd.dev/build:24
    volumes:
      - /data:/host/data
    commands:
      - sudo chown -R nixuser:nixbld /woodpecker
      - tar -czf "/host/data/test/${CI_COMMIT_SHA}.tar.gz" "/host/data/test/${CI_COMMIT_SHA}/"
      - sudo mv "/host/data/test/${CI_COMMIT_SHA}.tar.gz" "/host/data/test/${CI_COMMIT_SHA}/"
      - echo "Test data tar.gz     -> https://ci.2nd.dev/testdata/${CI_COMMIT_SHA}/${CI_COMMIT_SHA}.tar.gz"
      - echo "Test data URL        -> https://ci.2nd.dev/testdata/${CI_COMMIT_SHA}/"

  - name: tar-and-print-codecov-data
    when:
      - evaluate: CI_CODECOV_PIPELINE == "true"
    image: registry.2nd.dev/build:24
    volumes:
      - /data:/host/data
    commands:
      - tar -czf "/host/data/codecov/${CI_COMMIT_SHA}.tar.gz" "/host/data/codecov/${CI_COMMIT_SHA}/"
      - sudo mv "/host/data/codecov/${CI_COMMIT_SHA}.tar.gz" "/host/data/codecov/${CI_COMMIT_SHA}/"
      - echo "Code Coverage tar.gz -> https://ci.2nd.dev/codecov/${CI_COMMIT_SHA}/${CI_COMMIT_SHA}.tar.gz"
      - echo "Code Coverage URL    -> https://ci.2nd.dev/codecov/${CI_COMMIT_SHA}/html/index.html"

  - name: generate-rustdocs
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://gitlab.com/ark-bitcoin/bark"'
    failure: ignore
    image: registry.2nd.dev/build:24
    volumes:
      - /data:/host/data
    commands:
      - nix develop .#default --command bash -c "just rustdocs"
      - sudo cp -r rustdocs /host/data/
      - bash contrib/generate-index.sh /host/data/rustdocs/doc
      - echo "rustdocs -> https://rustdocs.2nd.dev/master/"

  - name: check-versions
    when:
      - event: tag
    image: registry.2nd.dev/build:24
    commands:
      - bash ./contrib/check-versions.sh "${CI_COMMIT_TAG}"

  - name: check-gitlab-release
    when:
      - event: tag
    image: registry.2nd.dev/build:24
    commands:
      - bash ./contrib/check-gitlab-release.sh "${CI_COMMIT_TAG}"

depends_on:
  - main
  - tests
  - tests-codecov