when:
  - event: pull_request
  - event: manual
  - event: tag
  - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://codeberg.org/ark-bitcoin/bark"'

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: push-github-mirror
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://codeberg.org/ark-bitcoin/bark"'
    failure: ignore
    image: appleboy/drone-git-push@sha256:b7fbe3c66653f36d5898ccaf142be65274dc18ba260783b3a99ccc3098eed7b2
    settings:
      remote: git@github.com:ark-bitcoin/bark.git
      branch: master
      local_branch: master
      force: true
      ssh_key:
        from_secret: GITHUB_LOGIN_TOKEN

  - name: push-codeberg-mirror
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://gitlab.com/ark-bitcoin/bark"'
    failure: ignore
    image: appleboy/drone-git-push@sha256:b7fbe3c66653f36d5898ccaf142be65274dc18ba260783b3a99ccc3098eed7b2
    settings:
      remote: git@codeberg.org:ark-bitcoin/bark.git
      branch: master
      local_branch: master
      force: true
      ssh_key:
        from_secret: CODEBERG_LOGIN_TOKEN

  - name: prechecks
    image: registry.2nd.dev/build:24
    volumes:
      - /data:/host/data
    commands:
      - sudo chown -R nixuser:nixbld /woodpecker
      - git log --oneline | head -n 1
      - rm -rf "/host/data/test/${CI_COMMIT_SHA}/" || true
      - rm -rf "/host/data/codecov/${CI_COMMIT_SHA}/" || true
      - nix develop .#default --command bash -c "just prechecks"
