when:
  - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://gitlab.com/ark-bitcoin/bark"'

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: parse-versions
    image: registry.2nd.dev/build:26
    commands:
      - sudo chown -R nixuser:nixbld /woodpecker
      - git rev-parse HEAD > VERSION
      - cat VERSION

  - name: build-server
    depends_on: parse-versions
    image: registry.2nd.dev/build:26
    environment:
      SDKROOT: /usr/local/osxcross/SDK/MacOSX15.4.sdk
    commands:
      - cat VERSION
      - just release-server
      - cp ./target/x86_64-unknown-linux-gnu/release/captaind captaind-linux-x86_64
      - cp ./target/x86_64-unknown-linux-gnu/release/watchmand watchmand-linux-x86_64

  - name: build-and-push-captaind-to-registry
    failure: ignore
    depends_on: build-server
    # When this task fails make sure the sha256 is still available.
    #  You can verify using command: `skopeo inspect docker://quay.io/buildah/stable`
    #  or `skopeo inspect docker://quay.io/buildah/stable@sha256:5f67b6ece887c7ffbc063d174fd95f057a76b218adf1160c7a5c3d63997efd4b`
    image: quay.io/buildah/stable@sha256:5f67b6ece887c7ffbc063d174fd95f057a76b218adf1160c7a5c3d63997efd4b
    environment:
      REGISTRY_LOGIN_TOKEN:
        from_secret: REGISTRY_LOGIN_TOKEN
    pull: true
    privileged: true
    commands:
      - cat VERSION
      - echo $REGISTRY_LOGIN_TOKEN | buildah login -u registry --password-stdin registry.2nd.dev
      # Build the containers
      - buildah build -f ./.woodpecker/images/releases/captaind/Dockerfile --tag "registry.2nd.dev/captaind:$(cat VERSION)" .
      # Push containers to registry.2nd.dev
      - buildah push "registry.2nd.dev/captaind:$(cat VERSION)"
      - curl "http://192.168.2.10:7777/zulip?topic=deployment&type=bell&message=captaind%20$(cat VERSION)%20is%20ready%20for%20deployment."
