when:
  - event: tag
    ref: refs/tags/server-*

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: parse-versions
    when:
      - event: tag
        ref: refs/tags/server-*
    image: registry.2nd.dev/build:25
    commands:
      - sudo chown -R nixuser:nixbld /woodpecker
      - bash ./contrib/parse-versions.sh "${CI_COMMIT_TAG}" > VERSION
      - cat VERSION

  - name: build-server
    when:
      - event: tag
        ref: refs/tags/server-*
    depends_on: parse-versions
    image: registry.2nd.dev/build:25
    environment:
      SDKROOT: /usr/local/osxcross/SDK/MacOSX15.4.sdk
    commands:
      - cat VERSION
      - just release-server
      - cp ./target/x86_64-unknown-linux-gnu/release/captaind captaind-linux-x86_64
      - cp ./target/x86_64-unknown-linux-gnu/release/watchmand watchmand-linux-x86_64

  - name: build-and-push-captaind-to-registry
    when:
      - event: tag
        ref: refs/tags/server-*
    failure: ignore
    depends_on: build-server
    # When this task fails make sure the sha256 is still available.
    #  You can verify using command: `skopeo inspect docker://quay.io/buildah/stable`
    #  or `skopeo inspect docker://quay.io/buildah/stable@sha256:5f67b6ece887c7ffbc063d174fd95f057a76b218adf1160c7a5c3d63997efd4b`
    image: quay.io/buildah/stable@sha256:5f67b6ece887c7ffbc063d174fd95f057a76b218adf1160c7a5c3d63997efd4b
    environment:
      REGISTRY_LOGIN_TOKEN:
        from_secret: REGISTRY_LOGIN_TOKEN
    pull: true
    privileged: true
    commands:
      - cat VERSION
      - echo $REGISTRY_LOGIN_TOKEN | buildah login -u registry --password-stdin registry.2nd.dev
      # Build the containers
      - buildah build -f ./.woodpecker/images/releases/captaind/Dockerfile --tag registry.2nd.dev/captaind:latest .
      # Push containers to registry.2nd.dev
      - buildah push registry.2nd.dev/captaind:latest
      # Tag containers with specific version number for registry.2nd.dev
      - buildah tag registry.2nd.dev/captaind:latest "registry.2nd.dev/captaind:$(cat VERSION)"
      # Push containers with specific version number to registry.2nd.dev
      - buildah push "registry.2nd.dev/captaind:$(cat VERSION)"

  - name: push-captaind-to-docker
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "tag" && CI_COMMIT_REF contains "refs/tags/server-" && CI_REPO_URL == "https://gitlab.com/ark-bitcoin/bark"'
    failure: ignore
    depends_on: build-and-push-captaind-to-registry
    # When this task fails make sure the sha256 is still available.
    #  You can verify using command: `skopeo inspect docker://quay.io/buildah/stable`
    #  or `skopeo inspect docker://quay.io/buildah/stable@sha256:5f67b6ece887c7ffbc063d174fd95f057a76b218adf1160c7a5c3d63997efd4b`
    image: quay.io/buildah/stable@sha256:5f67b6ece887c7ffbc063d174fd95f057a76b218adf1160c7a5c3d63997efd4b
    environment:
      REGISTRY_LOGIN_TOKEN:
        from_secret: REGISTRY_LOGIN_TOKEN
      DOCKER_LOGIN_TOKEN:
        from_secret: DOCKER_LOGIN_TOKEN
    pull: true
    privileged: true
    commands:
      - cat VERSION
      - echo $DOCKER_LOGIN_TOKEN | buildah login -u secondark --password-stdin docker.io
      - echo $REGISTRY_LOGIN_TOKEN | buildah login -u registry --password-stdin registry.2nd.dev
      # Pull containers from registry.2nd.dev
      - buildah pull registry.2nd.dev/captaind:latest
      # Tag containers for docker.io
      - buildah tag registry.2nd.dev/captaind:latest docker.io/secondark/captaind:latest
      # Push containers to docker.io
      - buildah push docker.io/secondark/captaind:latest
      # Tag containers with specific version number for docker.io
      - buildah tag registry.2nd.dev/captaind:latest "docker.io/secondark/captaind:$(cat VERSION)"
      # Push containers with specific version number to docker.io
      - buildah push "docker.io/secondark/captaind:$(cat VERSION)"

  - name: release-server
    when:
      - event: tag
        ref: refs/tags/server-*
    depends_on: build-server
    image: registry.2nd.dev/build:25
    commands:
      - cat VERSION
      - cd ./target
      - cp x86_64-unknown-linux-gnu/release/captaind "captaind-$(cat ../VERSION)-linux-x86_64"
      - cp x86_64-unknown-linux-gnu/release/watchmand "watchmand-$(cat ../VERSION)-linux-x86_64"
      - sha256sum "captaind-$(cat ../VERSION)-linux-x86_64" > SHA256SUMS
      - sha256sum "watchmand-$(cat ../VERSION)-linux-x86_64" >> SHA256SUMS

  - name: publish-server-forgejo
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "tag" && CI_COMMIT_REF contains "refs/tags/server-" && CI_REPO_URL != "https://gitlab.com/ark-bitcoin/bark"'
    depends_on: release-server
    image: woodpeckerci/plugin-release@sha256:f746ad9a4e652d7b793d6aafdab3df01e7640abf66b49333ebae26edd1678c64
    settings:
      files:
        - "./target/captaind-*-linux-x86_64"
        - "./target/watchmand-*-linux-x86_64"
        - "./target/SHA256SUMS"
      api_key:
        from_secret: RELEASE

  - name: publish-server-gitlab
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "tag" && CI_COMMIT_REF contains "refs/tags/server-" && CI_REPO_URL == "https://gitlab.com/ark-bitcoin/bark"'
    depends_on: release-server
    image: registry.2nd.dev/build:25
    environment:
      GITLAB_TOKEN:
        from_secret: GITLAB_LOGIN_TOKEN
    commands:
      - |
        echo "Checking release for tag ${CI_COMMIT_TAG}"
        RESPONSE=$(curl --silent --request GET \
          --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
          "https://gitlab.com/api/v4/projects/75519706/releases/${CI_COMMIT_TAG}")

        if echo "$RESPONSE" | jq -e '.tag_name' > /dev/null; then
          RELEASE_ID=$(echo "$RESPONSE" | jq '.id')
          echo "Release exists: ID $RELEASE_ID"
        else
          echo "Creating new release"
          RESPONSE=$(curl --silent --request POST \
            --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            --header "Content-Type: application/json" \
            --data '{
              "name": "'${CI_COMMIT_TAG}'",
              "tag_name": "'${CI_COMMIT_TAG}'",
              "description": "Automated release from Woodpecker CI",
              "milestones": [],
              "assets": { "links": [] }
            }' \
            "https://gitlab.com/api/v4/projects/75519706/releases")
          RELEASE_ID=$(echo "$RESPONSE" | jq '.id')
          echo "Created release: ID $RELEASE_ID"
        fi
        
        ASSET_LINKS=""
        for file in ./target/captaind-*-linux-x86_64 ./target/watchmand-*-linux-x86_64 ./target/SHA256SUMS; do
          if [ -f "$file" ]; then
            FILENAME=$(basename "$file")
            echo "Uploading $FILENAME"
            UPLOAD_RESPONSE=$(curl --silent --request POST \
              --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
              --header "Content-Type: application/octet-stream" \
              --data-binary "@$file" \
              "https://gitlab.com/api/v4/projects/75519706/uploads")

            UPLOAD_URL=$(echo "$UPLOAD_RESPONSE" | jq -r '.url')
            if [ "$UPLOAD_URL" != "null" ]; then
              # Add to links array
              LINK_JSON=$(printf '{"name": "%s", "url": "%s", "link_type": "other"}' "$FILENAME" "$UPLOAD_URL")
              if [ -z "$ASSET_LINKS" ]; then
                ASSET_LINKS="[$LINK_JSON"
              else
                ASSET_LINKS="$ASSET_LINKS, $LINK_JSON"
              fi
            fi
          else
            echo "Warning: $file not found"
          fi
        done
        ASSET_LINKS="$ASSET_LINKS]"
        
        if [ "$ASSET_LINKS" != "[]" ]; then
          echo "Linking assets to release"
          curl --silent --request PUT \
            --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            --header "Content-Type: application/json" \
            --data "{\"assets\": {\"links\": $ASSET_LINKS}}" \
            "https://gitlab.com/api/v4/projects/75519706/releases/${CI_COMMIT_TAG}" \
            --output /dev/null
          echo "Assets linked successfully"
        fi
        
        echo "GitLab release: https://gitlab.com/ark-bitcoin/bark/-/releases/${CI_COMMIT_TAG}"
