when:
  - event: pull_request
  - event: manual
  - event: tag
  - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://gitlab.com/ark-bitcoin/bark"'

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: check-commits
    image: registry.2nd.dev/build:25
    commands:
      - sudo chown -R nixuser:nixbld /woodpecker
      - git log --oneline | head -n 1
      - nix develop .#default --command bash -c "just check-commits"
      - git log --oneline | head -n 1

  - name: build
    depends_on: check-commits
    image: registry.2nd.dev/build:25
    volumes:
      - /data:/host/data
    commands:
      - git log --oneline | head -n 1
      - >
        nix develop .#default --command bash -c "
          cargo version &&
          cargo build --workspace
        "


  - name: compare-static-files
    depends_on: check-commits
    image: registry.2nd.dev/build:25
    commands:
      - >
        nix develop .#default --command bash -c "
          cargo run --example dump-sqlite-schema            > bark/schema.sql
          cargo run --example dump-server-postgres-schema   > server/schema.sql
          sed -i '/^-- Dumped by .*$/d'   server/schema.sql
          sed -i '/^-- Dumped from .*$/d' server/schema.sql
          sed -i '/^.restrict.*$/d'       server/schema.sql
          sed -i '/^.unrestrict.*$/d'     server/schema.sql
          chmod 644 bark/schema.sql
          chmod 644 server/schema.sql
        "
      - bash contrib/check-clean-diff.sh bark/schema.sql
      - bash contrib/check-clean-diff.sh server/schema.sql

  - name: test-unit
    depends_on: build
    image: registry.2nd.dev/build:25
    commands:
      - git log --oneline | head -n 1
      - >
        nix develop .#default --command bash -c "
          cargo test --workspace --exclude ark-testing
        "

  - name: use-bark-as-dependency
    depends_on: test-unit
    image: registry.2nd.dev/build:25
    commands:
      - >
        nix develop .#default --command bash -c "
          cargo init barktest &&
          cd barktest &&
          cargo add bark-wallet &&
          cargo update &&
          cargo build
        "

  - name: bark-as-libs
    depends_on: test-unit
    image: registry.2nd.dev/build:25
    commands:
      - >
        nix develop .#default --command bash -c "
          cargo build -p bark-wallet      --no-default-features --features=\"\" &&
          cargo build -p bark-bitcoin-ext --no-default-features --features=\"\" &&
          cargo build -p ark-lib          --no-default-features --features=\"\"
        "

  - name: check-release
    depends_on: test-unit
    image: registry.2nd.dev/build:25
    commands:
      - >
        nix develop .#default --command bash -c "
          cargo check --release -p bark-cli &&
          cargo check --release -p bark-server
        "

  - name: test-integration-esplora
    when:
      - event: push
        branch: master
    depends_on: bark-as-libs
    image: registry.2nd.dev/build:25
    volumes:
      - /data:/host/data
      - tmpfs:/dev/shm:rw
    environment:
      CHAIN_SOURCE: esplora
      TEST_DIRECTORY: ./test/esplora
      RUST_TEST_THREADS: 2
      BARK_COMMAND_TIMEOUT_MILLIS: 120000
      TX_PROPAGATION_TIMEOUT: 30000
    privileged: true
    commands:
      - git log --oneline | head -n 1
      - export CAPTAIND_EXEC=${CI_WORKSPACE}/target/debug/captaind
      - export BARK_EXEC=${CI_WORKSPACE}/target/debug/bark
      - bash ./contrib/ci-run-test.sh test-integration

  - name: test-integration-mempool
    depends_on: bark-as-libs
    image: registry.2nd.dev/build:25
    volumes:
      - /data:/host/data
      - tmpfs:/dev/shm:rw
    environment:
      CHAIN_SOURCE: mempool
      TEST_DIRECTORY: ./test/mempool
      RUST_TEST_THREADS: 2
      BARK_COMMAND_TIMEOUT_MILLIS: 120000
      TX_PROPAGATION_TIMEOUT: 30000
    privileged: true
    commands:
      - git log --oneline | head -n 1
      - export CAPTAIND_EXEC=${CI_WORKSPACE}/target/debug/captaind
      - export BARK_EXEC=${CI_WORKSPACE}/target/debug/bark
      - bash ./contrib/ci-run-test.sh test-integration

  - name: test-integration-btc29.1
    depends_on: bark-as-libs
    image: registry.2nd.dev/build:25
    volumes:
      - /data:/host/data
      - tmpfs:/dev/shm:rw
    environment:
      TEST_DIRECTORY: ./test/btc29
      RUST_TEST_THREADS: 2
      BARK_COMMAND_TIMEOUT_MILLIS: 120000
      TX_PROPAGATION_TIMEOUT: 30000
    privileged: true
    commands:
      - git log --oneline | head -n 1
      - export CAPTAIND_EXEC=${CI_WORKSPACE}/target/debug/captaind
      - export BARK_EXEC=${CI_WORKSPACE}/target/debug/bark
      - bash ./contrib/ci-run-test.sh test-integration

depends_on:
  - main
