when:
  - event: pull_request
  - event: manual
  - event: tag
  - event: push
    branch: master

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: check-commits
    image: registry.2nd.dev/build:17
    commands:
      - just check-commits

  - name: test-unit
    depends_on: check-commits
    image: registry.2nd.dev/build:17
    commands:
      - git log --oneline | head -n 1
      - just test-unit-all

  - name: build
    depends_on: check-commits
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    commands:
      - git log --oneline | head -n 1
      - cargo version
      - just build

  - name: aspd-default-config-file
    depends_on: build
    image: registry.2nd.dev/build:17
    commands:
      - just default-aspd-config
      - bash contrib/check-clean-default-config.sh

  - name: use-bark-as-dependency
    depends_on: build
    image: registry.2nd.dev/build:17
    commands:
      - cargo init barktest && cd barktest
      - cargo add bark-client
      - cargo update
      - cargo build

  - name: test-integration-esplora
    depends_on: build
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    environment:
      BITCOIND_EXEC: /bitcoin/29.0/bin/bitcoind
      LIGHTNINGD_EXEC: /lightning/25.02/bin/lightningd
      ELECTRS_EXEC: /root/.cargo/bin/electrs
      CHAIN_SOURCE: esplora
      TEST_DIRECTORY: ./test/esplora
      TEST_POSTGRES_HOST: localhost
      RUST_TEST_THREADS: 4
    commands:
      - git log --oneline | head -n 1
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - ls -al $${ELECTRS_EXEC}
      - service postgresql start
      - just test-integration-all || echo $? > /tmp/test_exit_code
      - mkdir -p "/host/data/test/${CI_COMMIT_SHA}/"
      - cp -r test/* "/host/data/test/${CI_COMMIT_SHA}/"
      - echo "Test data -> https://ci.2nd.dev/testdata/${CI_COMMIT_SHA}/"
      - |
        if [ -f /tmp/test_exit_code ]; then
          code=$(cat /tmp/test_exit_code)
          echo "Tests failed with exit code $code."
          exit $code
        fi

  - name: test-integration-btc29.0
    depends_on: build
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    environment:
      BITCOIND_EXEC: /bitcoin/29.0/bin/bitcoind
      LIGHTNINGD_EXEC: /lightning/25.02/bin/lightningd
      TEST_DIRECTORY: ./test/btc29
      TEST_POSTGRES_HOST: localhost
      RUST_TEST_THREADS: 4
    commands:
      - git log --oneline | head -n 1
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - ls -al $${BITCOIND_EXEC}
      - ls -al $${LIGHTNINGD_EXEC}
      - service postgresql start
      - just test-integration-all || echo $? > /tmp/test_exit_code
      - mkdir -p "/host/data/test/${CI_COMMIT_SHA}/"
      - cp -r test/* "/host/data/test/${CI_COMMIT_SHA}/"
      - echo "Test data -> https://ci.2nd.dev/testdata/${CI_COMMIT_SHA}/"
      - |
        if [ -f /tmp/test_exit_code ]; then
          code=$(cat /tmp/test_exit_code)
          echo "Tests failed with exit code $code."
          exit $code
        fi

depends_on:
  - main
