when:
  - event: pull_request
  - event: manual
  - event: tag
  - evaluate: 'CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "master" && CI_REPO_URL == "https://codeberg.org/ark-bitcoin/bark"'

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: check-commits
    image: registry.2nd.dev/build:21
    commands:
      - git log --oneline | head -n 1
      - just check-commits
      - git log --oneline | head -n 1

  - name: test-unit
    depends_on: check-commits
    image: registry.2nd.dev/build:21
    commands:
      - git log --oneline | head -n 1
      - >
        nix --extra-experimental-features 'nix-command flakes' develop .#default --command bash -c "
          cargo test --workspace --exclude ark-testing
        "

  - name: build
    depends_on: check-commits
    image: registry.2nd.dev/build:21
    volumes:
      - /data:/host/data
    commands:
      - git log --oneline | head -n 1
      - >
        nix --extra-experimental-features 'nix-command flakes' develop .#default --command bash -c "
          cargo version &&
          cargo build --workspace
        "

  - name: generated-static-files
    depends_on: build
    image: registry.2nd.dev/build:21
    environment:
      TEST_POSTGRES_HOST: localhost
    commands:
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop .#default
      - just default-server-config
      - bash contrib/check-clean-diff.sh server/config.default.toml
      - just dump-bark-sql-schema
      - bash contrib/check-clean-diff.sh bark/schema.sql
      - service postgresql start
      - just dump-server-sql-schema
      - bash contrib/check-clean-diff.sh server/schema.sql

  - name: use-bark-as-dependency
    depends_on: build
    image: registry.2nd.dev/build:21
    commands:
      - >
        nix --extra-experimental-features 'nix-command flakes' develop .#default --command bash -c "
          cargo init barktest &&
          cd barktest &&
          cargo add bark-wallet &&
          cargo update && cargo build
        "

  - name: bark-as-libs
    depends_on: build
    image: registry.2nd.dev/build:21
    commands:
      - >
        nix --extra-experimental-features 'nix-command flakes' develop .#default --command bash -c "
          cargo build -p bark-wallet      --no-default-features --features=\"\" &&
          cargo build -p bark-bitcoin-ext --no-default-features --features=\"\" &&
          cargo build -p ark-lib          --no-default-features --features=\"\"
        "

  - name: test-integration-esplora
    when:
      - event: push
        branch: master
    depends_on: build
    image: registry.2nd.dev/build:21
    volumes:
      - /data:/host/data
    environment:
      CHAIN_SOURCE: esplora
      TEST_DIRECTORY: ./test/esplora
      TEST_POSTGRES_HOST: localhost
      RUST_TEST_THREADS: 4
    commands:
      - git log --oneline | head -n 1
      - export CAPTAIND_EXEC=${CI_WORKSPACE}/target/debug/captaind
      - export BARK_EXEC=${CI_WORKSPACE}/target/debug/bark
      - service postgresql start
      - bash ./contrib/ci-run-test.sh test-integration

  - name: test-integration-mempool
    depends_on: build
    image: registry.2nd.dev/build:21
    volumes:
      - /data:/host/data
    environment:
      CHAIN_SOURCE: mempool
      TEST_DIRECTORY: ./test/mempool
      TEST_POSTGRES_HOST: localhost
      RUST_TEST_THREADS: 4
    commands:
      - git log --oneline | head -n 1
      - export CAPTAIND_EXEC=${CI_WORKSPACE}/target/debug/captaind
      - export BARK_EXEC=${CI_WORKSPACE}/target/debug/bark
      - service postgresql start
      - bash ./contrib/ci-run-test.sh test-integration

  - name: test-integration-btc29.0
    depends_on: build
    image: registry.2nd.dev/build:21
    volumes:
      - /data:/host/data
    environment:
      TEST_DIRECTORY: ./test/btc29
      TEST_POSTGRES_HOST: localhost
      RUST_TEST_THREADS: 4
    commands:
      - git log --oneline | head -n 1
      - export CAPTAIND_EXEC=${CI_WORKSPACE}/target/debug/captaind
      - export BARK_EXEC=${CI_WORKSPACE}/target/debug/bark
      - service postgresql start
      - bash ./contrib/ci-run-test.sh test-integration

depends_on:
  - main
