when:
  - event: pull_request
  - event: manual
  - event: tag
  - event: push
    branch: master

clone:
  - name: clone
    image: woodpeckerci/plugin-git@sha256:2aaacedd7da067f2f6b54a3ef3d39cc69cc0c1152e377fd8df266bd34acd317e
    settings:
      partial: false
      depth: 100
      lfs: false

steps:
  - name: check-commits
    image: registry.2nd.dev/build:17
    commands:
      - just check-commits

  - name: test-unit
    depends_on: check-commits
    image: registry.2nd.dev/build:17
    commands:
      - git log --oneline | head -n 1
      - just test-unit-all-codecov

  - name: build
    depends_on: check-commits
    image: registry.2nd.dev/build:17
    commands:
      - git log --oneline | head -n 1
      - cargo version
      - just build-codecov

  - name: test-integration-btc29.0
    failure: ignore
    depends_on: build
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    environment:
      BITCOIND_EXEC: /bitcoin/29.0/bin/bitcoind
      LIGHTNINGD_EXEC: /lightning/25.02/bin/lightningd
      TEST_DIRECTORY: ./test/btc29
      TEST_POSTGRES_HOST: localhost
    commands:
      - git log --oneline | head -n 1
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - ls -al $${BITCOIND_EXEC}
      - ls -al $${LIGHTNINGD_EXEC}
      - service postgresql start
      - just test-integration-all-codecov || echo $? > /tmp/test_exit_code
      - mkdir -p "/host/data/test/${CI_COMMIT_SHA}/"
      - cp -r test/* "/host/data/test/${CI_COMMIT_SHA}/"
      - echo "Test data -> https://ci.2nd.dev/testdata/${CI_COMMIT_SHA}/"
      - |
        if [ -f /tmp/test_exit_code ]; then
          code=$(cat /tmp/test_exit_code)
          echo "Tests failed with exit code $code."
          exit $code
        fi

  - name: code-coverage
    failure: ignore
    depends_on: test-integration-btc29.0
    image: registry.2nd.dev/build:17
    volumes:
      - /data:/host/data
    commands:
      - just codecov-report
      - mkdir -p "/host/data/codecov/${CI_COMMIT_SHA}/"
      - cp -r target/debug/codecov/* "/host/data/codecov/${CI_COMMIT_SHA}/"
      - echo "Coverage -> https://ci.2nd.dev/codecov/${CI_COMMIT_SHA}/html/index.html"

depends_on:
  - main
